# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 522)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gridGroupBox.setGeometry(QtCore.QRect(10, 200, 371, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 102, 102, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_5.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 4, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,153, 0, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 0, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_5.addWidget(self.pushButton_13, 3, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 2, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(63)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 123, 231, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 0, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 5, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_5.addWidget(self.pushButton_15, 3, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        self.pushButton_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 5, 1, 1, 2)
        self.pushButton_49 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_49.sizePolicy().hasHeightForWidth())
        self.pushButton_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout_5.addWidget(self.pushButton_49, 2, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_5.addWidget(self.pushButton_16, 4, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: rgba(160, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_5.addWidget(self.pushButton_14, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 3, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_5.addWidget(self.pushButton_12, 4, 3, 1, 1)
        self.pushButton_69 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_69.sizePolicy().hasHeightForWidth())
        self.pushButton_69.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setWeight(63)
        self.pushButton_69.setFont(font)
        self.pushButton_69.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_69.setObjectName("pushButton_69")
        self.gridLayout_5.addWidget(self.pushButton_69, 2, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(63)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 160, 0.60); /* лёгкая прозрачность */\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    color: #3c4043;\n"
"    font-family: \"Google Sans\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 6px 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(246, 249, 254, 0.3);\n"
"    color: #174ea6;\n"
"    border: 1px solid rgba(23, 78, 166, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(224, 224, 224, 0.4);\n"
"    border: 1px solid rgba(60, 64, 67, 0.5);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #4285f4;\n"
"    outline: none;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 3, 4, 3, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setEnabled(False)
        self.widget.setGeometry(QtCore.QRect(0, 0, 391, 521))
        self.widget.setStyleSheet("""
            QWidget {
                background-image: url("/home/assan/Desktop/PyQt6 learning/calculator/background.png");
                background-repeat: no-repeat;
                background-position: center;
                border-radius: 20px;
            }
        """)

        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 371, 181))
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 0.4);")
        self.lineEdit.setObjectName("lineEdit")
        self.widget.raise_()
        self.gridGroupBox.raise_()
        self.lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_9.setText(_translate("MainWindow", "-"))
        self.pushButton_10.setText(_translate("MainWindow", "7"))
        self.pushButton_11.setText(_translate("MainWindow", "1"))
        self.pushButton_6.setText(_translate("MainWindow", "/"))
        self.pushButton_13.setText(_translate("MainWindow", "6"))
        self.pushButton_5.setText(_translate("MainWindow", "9"))
        self.pushButton_7.setText(_translate("MainWindow", "*"))
        self.pushButton_2.setText(_translate("MainWindow", "С"))
        self.pushButton_15.setText(_translate("MainWindow", "4"))
        self.pushButton_3.setText(_translate("MainWindow", "0"))
        self.pushButton_49.setText(_translate("MainWindow", "8"))
        self.pushButton_16.setText(_translate("MainWindow", "2"))
        self.pushButton_14.setText(_translate("MainWindow", "+"))
        self.pushButton.setText(_translate("MainWindow", "5"))
        self.pushButton_12.setText(_translate("MainWindow", "3"))
        self.pushButton_69.setText(_translate("MainWindow", "%"))
        self.pushButton_4.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
